import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Provider from '../context/AuthContext';
import RefContextProvider from '../context/RefContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Link Sharing App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Provider>
          <RefContextProvider>{children}</RefContextProvider>
        </Provider>
      </body>
    </html>
  );
}
